DROP DATABASE IF EXISTS soundcloud;
CREATE DATABASE IF NOT EXISTS `soundcloud` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `soundcloud`;

-- User Table
CREATE TABLE User(
	USER_ID				INT				PRIMARY KEY,
    NAME				VARCHAR(100)	NOT NULL,
    BIRTH_DATE			DATE			NOT NULL,
    PROFILE_IMG			VARCHAR(500)	NOT NULL,
    HEADER_IMG			VARCHAR(500)	NOT NULL,
    USER_GENDER			CHAR(1),
    REGISTER_TIMESTAMP	TIMESTAMP	NOT NULL,
    USER_EMAIL			VARCHAR(50)		NOT NULL,
    HASHED_PASSWORD		VARCHAR(64)		NOT NULL,
    ADDRESS				VARCHAR(100),
    DESCRIPTION			VARCHAR(500),
	COUNTRY				VARCHAR(20)
);
-- Track Table
CREATE TABLE Track(
	TRACK_ID			INT				PRIMARY KEY,
    USER_ID				INT,
    TRACK_NAME			VARCHAR(50)		NOT NULL,
    TRACK_LINK			VARCHAR(100)	NOT NULL,
    UPLOAD_TIMESTAMP	TIMESTAMP		NOT NULL,
    TRACK_IMG			VARCHAR(100),
    DESCRIPTION			VARCHAR(500),
    RELEASE_TIMESTAMP	TIMESTAMP,
    CONSTRAINT Track_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);
-- Album Table
CREATE TABLE Album(
	ALBUM_ID			INT				PRIMARY KEY,
    USER_ID				INT,
    ALBUM_NAME			VARCHAR(50)		NOT NULL,
    CREATED_TIMESTAMP	TIMESTAMP		NOT NULL,
    ALBUM_IMG			VARCHAR(100)	NOT NULL,
    DESCRIPTION			VARCHAR(500)	NOT NULL,
    ALBUM_LINK			VARCHAR(100)	NOT NULL,
    RELEASE_TIMESTAMP	TIMESTAMP,
    CONSTRAINT Album_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);
-- Operator Table
CREATE TABLE Operator(
	OPERATOR_ID			INT				PRIMARY KEY,
    OPERATOR_NAME		VARCHAR(50)		NOT NULL,
    OPERATOR_IMG		VARCHAR(100)	NOT NULL,
    OPERATOR_EMAIL		VARCHAR(50)		NOT NULL,
    OPERATOR_STATUS		INT				NOT NULL,
    OPERATOR_HEADER_IMG	VARCHAR(100)	NOT NULL,
    OPERATOR_COUNTRY	VARCHAR(20)		NOT NULL
);
-- Post Table
CREATE TABLE Post(
	POST_ID				INT				PRIMARY KEY,
    USER_ID				INT,
    POST_DETAIL			VARCHAR(500)	NOT NULL,
    POST_TIMESTAMP		TIMESTAMP		NOT NULL,
    CONSTRAINT Post_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);
-- Station Table
CREATE TABLE Station(
	STATION_ID			INT				PRIMARY KEY,
    USER_ID				INT,
    STATION_NAME		VARCHAR(100)	NOT NULL,
    STATION_IMG			VARCHAR(100)	NOT NULL,
    CONSTRAINT Station_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);
-- License Table
CREATE TABLE License(
	LICENSE_ID			INT				PRIMARY KEY,
    TRACK_ID			INT,
    LICENSE_TYPE		VARCHAR(100)	NOT NULL,
    CONSTRAINT License_FK_USER_ID FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- PaymentTransactionLog Table
CREATE TABLE PaymentTransactionLog(
	REF_ID				INT				PRIMARY KEY,
    USER_ID				INT,
    LOG_TIMESTAMP		TIMESTAMP		NOT NULL,
    RECEIVER_ID			INT				NOT NULL,
    AMOUNT				DECIMAL(10,2)	NOT NULL,
    PAYMENT_TYPE		INT				NOT NULL,
    CARD_NUM			VARCHAR(20),
    CARD_TYPE			VARCHAR(20),
    CARD_NAME			VARCHAR(100),
    CARD_EXP			VARCHAR(10),
    BANK_NAME			VARCHAR(50),
    BANK_ACCOUNT		VARCHAR(50),
    CONSTRAINT PaymentTransactionLog_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);
-- UserMessageUser Table
CREATE TABLE UserMessageUser(
	MESSAGE_ID			INT,
    USER_ID1			INT,
    USER_ID2			INT,
    MESSAGE				VARCHAR(100)	NOT NULL,
    TIMESTAMP			TIMESTAMP		NOT NULL,
    CONSTRAINT UserMessageUser_PK_USER_ID1 PRIMARY KEY (USER_ID1,USER_ID2,MESSAGE_ID),
    CONSTRAINT UserMessageUser_FK_USER_ID1 FOREIGN KEY (USER_ID1) REFERENCES User(USER_ID),
    CONSTRAINT UserMessageUser_FK_USER_ID2 FOREIGN KEY (USER_ID2) REFERENCES User(USER_ID)
);
-- UserBlockUser Table
CREATE TABLE UserBlockUser(
	USER_ID1			INT,
    USER_ID2			INT,
    TIMESTAMP_AT_BLOCK	TIMESTAMP		 NOT NULL,
    CONSTRAINT UserBlockUser_PK_USER_ID1 PRIMARY KEY (USER_ID1,USER_ID2),
    CONSTRAINT UserBlockUser_FK_USER_ID1 FOREIGN KEY (USER_ID1) REFERENCES User(USER_ID),
    CONSTRAINT UserBlockUser_FK_USER_ID2 FOREIGN KEY (USER_ID2) REFERENCES User(USER_ID)
);
-- UserFollowUser Table
CREATE TABLE UserFollowUser(
	USER_ID1			INT,
    USER_ID2			INT,
    TIMESTAMP_AT_FOLLOW	TIMESTAMP		  NOT NULL,
    CONSTRAINT UserFollowUser_PK_USER_ID1 PRIMARY KEY (USER_ID1,USER_ID2),
    CONSTRAINT UserFollowUser_FK_USER_ID1 FOREIGN KEY (USER_ID1) REFERENCES User(USER_ID),
    CONSTRAINT UserFollowUser_FK_USER_ID2 FOREIGN KEY (USER_ID2) REFERENCES User(USER_ID)
);
-- UserReportTrack Table
CREATE TABLE UserReportTrack(
	REPORT_ID			INT,
    USER_ID				INT,
    TRACK_ID			INT,
    TIMESTAMP_AT_REPORT	TIMESTAMP		  NOT NULL,
    CONSTRAINT UserReportTrack_PK PRIMARY KEY (REPORT_ID,USER_ID,TRACK_ID),
    CONSTRAINT UserFollowUser_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT UserFollowUser_FK_TRACK_ID FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- UserEditTrack Table
CREATE TABLE UserEditTrack(
	EDIT_ID				INT,
    USER_ID				INT,
    TRACK_ID			INT,
    TIMESTAMP_AT_EDIT	TIMESTAMP		  NOT NULL,
    CONSTRAINT UserEditTrack_PK PRIMARY KEY (EDIT_ID,USER_ID,TRACK_ID),
    CONSTRAINT UserEditTrack_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT UserEditTrack_FK_TRACK_ID FOREIGN KEY (USER_ID) REFERENCES Track(TRACK_ID)
);
-- UserCommentOnTrack Table
CREATE TABLE UserCommentOnTrack(
	COMMENT_ID			INT,
    USER_ID				INT,
    TRACK_ID			INT,
    COMMENT				VARCHAR(100)	NOT NULL,
    TIMESTAMP_AT_COMMENT	TIMESTAMP	NOT NULL,
    CONSTRAINT UserCommentOnTrack_PK PRIMARY KEY (COMMENT_ID,USER_ID,TRACK_ID),
    CONSTRAINT UserCommentOnTrack_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT UserCommentOnTrack_FK_TRACK_ID FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- UserLikeTrack Table
CREATE TABLE UserLikeTrack(
	USER_ID				INT,
    TRACK_ID			INT,
    TIMESTAMP_AT_LIKE	TIMESTAMP,
    CONSTRAINT UserLikeTrack_PK PRIMARY KEY (USER_ID,TRACK_ID),
    CONSTRAINT UserLikeTrack_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT UserLikeTrack_FK_TRACK_ID FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- UserRepostTrack Table
CREATE TABLE UserRepostTrack(
    REPOST_ID			INT,
    USER_ID				INT,
    TRACK_ID			INT,
    TIMESTAMP_AT_REPOST	TIMESTAMP		NOT NULL,
    PRIMARY KEY(REPOST_ID, USER_ID, TRACK_ID),
    CONSTRAINT Fk_User_ID_UserRepostTrack FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT Fk_Track_ID_UserRepostTrack FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- TrackHistory Table
CREATE TABLE TrackHistory(
    HISTORY_ID			INT,
    USER_ID				INT,
    TRACK_ID			INT,
    TIMESTAMP			TIMESTAMP		NOT NULL,
    PRIMARY KEY (HISTORY_ID, USER_ID, TRACK_ID),
    CONSTRAINT FK_User_ID_TrackHistory FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT FK_Track_ID_TrackHistory FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- UserDonateToTrack Table
CREATE TABLE UserDonateToTrack(
    DONATE_ID			INT,
    USER_ID				INT,
    TRACK_ID			INT,
    AMOUNT				DECIMAL(10,2)	NOT NULL,
    TIMESTAMP_AT_DONATE	TIMESTAMP		NOT NULL,
    PRIMARY KEY (DONATE_ID, USER_ID, TRACK_ID),
    CONSTRAINT FK_User_ID_UserDonateToTrack FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT FK_Track_ID_UserDonateToTrack FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- TrackInPost Table
CREATE TABLE TrackInPost(
    TRACK_ID			INT,
    POST_ID				INT,
    PRIMARY KEY (TRACK_ID, POST_ID),
    CONSTRAINT FK_Track_ID_TrackInPost FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID),
    CONSTRAINT FK_Post_ID_TrackInPost FOREIGN KEY (POST_ID) REFERENCES Post(POST_ID)
);
-- UsersPost Table
CREATE TABLE UsersPost(
    USER_ID				INT,
    POST_ID				INT,
    TIMESTAMP_AT_POST	TIMESTAMP		NOT NULL,
    POST_DESCRIPTION	VARCHAR(100)	NOT NULL,
    PRIMARY KEY (USER_ID, POST_ID),
    CONSTRAINT FK_User_ID_UsersPost FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT FK_Post_ID_UsersPost FOREIGN KEY (POST_ID) REFERENCES Post(POST_ID)
);
-- UserFollowStation Table
CREATE TABLE UserFollowStation(
    USER_ID				INT,
    STATION_ID			INT,
    TIMESTAMP_AT_FOLLOW	TIMESTAMP		NOT NULL,
    PRIMARY KEY (USER_ID, STATION_ID),
    CONSTRAINT FK_User_ID_UserFollowStation FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT FK_Station_ID_UserFollowStation FOREIGN KEY (STATION_ID) REFERENCES Station(STATION_ID)
);
-- TrackStoreAlbum Table
CREATE TABLE TrackStoreAlbum(
    ALBUM_ID			INT,
    TRACK_ID			INT,
    PRIMARY KEY (ALBUM_ID, TRACK_ID),
    CONSTRAINT FK_Album_ID_TrackStoreAlbum FOREIGN KEY (ALBUM_ID) REFERENCES Album(ALBUM_ID),
    CONSTRAINT FK_Track_ID_TrackStoreAlbum FOREIGN KEY (TRACK_ID) REFERENCES Track(TRACK_ID)
);
-- UserCallOperator Table
CREATE TABLE UserCallOperator(
    CALLING_ID			INT,
    USER_ID				INT,
    OPERATOR_ID			INT,
    TIMESTAMP_AT_CALL	TIMESTAMP    NOT NULL,
    PRIMARY KEY (CALLING_ID, USER_ID, OPERATOR_ID),
    CONSTRAINT FK_User_ID_UserCallOperator FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
    CONSTRAINT FK_Operator_ID_UserCallOperator FOREIGN KEY (OPERATOR_ID) REFERENCES Operator(OPERATOR_ID)
);